name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: team_ky3AzzeULE5oEF0nuGfuDvy2
          VERCEL_PROJECT_ID: prj_90OuwksWbPs9zUquQxfBUmYbK1uJ
